#!/bin/bash

#image="quay.io/kubespray/kubespray:v2.28.0"
image="ghcr.io/rwxrob/k8s.cicd/kubespray:v0.0.7"
podman run --rm -it \
	--mount type=bind,source="$(pwd)"/inventory,dst=/inventory \
	--mount type=bind,source="${HOME}"/.ssh/id_ed25519,dst=/root/.ssh/id_ed25519 \
	"$image" ansible-playbook -b -K -i /inventory/inventory.ini --private-key /root/.ssh/id_ed25519 upgrade-cluster.yml

#ghcr.io/rwxrob/k8s.cicd/kubespray:v0.0.1 bash
